use_frameworks!

platform :ios, '8.0'

target 'Mathematics_Example' do
  pod 'Mathematics', :path => '../'

  target 'Mathematics_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
